var l10n = {
  "en": {
    "language": "English",
    "translator": "",
    "unique": "Celebrate the 100th SDS with us by creating a project with 10 squares!\n<br/><br/>  Create a project that contains 10 squares on the screen at a time, and 10 squares only. It could be a train driving on a track, with the train made out of 7 squares, and the tracks made out of 3. It could be an Ice-cream simulator with the ice cream made out of 5 squares, and the ice cream machine made out of the other 5 squares. The possibilities are endless!<br/><br/> Wondering why we're making things out of 10 squares? It's because in math, 10 squared equals 100, and squared sounds like squares!<br/>",
    "standard": "o have your project added to this studio, please post a comment with a link. You can find a link to your project by clicking the ‘Embed’ button on the project page. The link will be directly below the Facebook logo.\n<br/>Please submit a single project made no earlier than one month before the start of this Design studio. However, you can update your project, and it'll be eligible again. If you have an older project that would fit, add some new features and feel free to submit the updated version!\n<br/>All projects must meet the community guidelines and be appropriate for all ages!\n<br/>It may take some time for your projects to be added. Please be patient, we add projects oldest to newest; no need to double post!\n<br/><br/>SDS (Scratch Design Studio) is a themed studio where any Scratcher can submit a project that matches the current theme so long as it meets the requirements shown above.\n Check out this project to see how new SDS curators are selected: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n Please do not simply ask to be a curator!\n<br/><br/>Do you have an idea for a future design studio? Visit the studio linked below, read the studio description, and then submit your idea in the form of a project here: <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Questions about Scratch Design Studio? Check out the Scratch Wiki's article on it: <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>Check out this account for new updates on the SDS, new SDS curators and more! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/>Credit to @SDScurator1 and @SDScurator2 for the thumbnail!",
    "curators": "The SDS is curated by"
  },
  "fr": {
    "language": "Français",
    "translator": " Traducido por <a href=\"https://scratch.mit.edu/users/coke11\">@coke11",
    "unique": " Celebrar el número 100 SDS con nosotros mediante la creación de un proyecto con 10 plazas!\n<br/><br/> Crear un proyecto que contiene 10 casillas en la pantalla a la vez, y sólo 10 casillas. Podría ser un tren de conducir en una pista, con el tren hecha de 7 plazas, y las pistas hechas fuera de 3. Podría ser un simulador de helado con el helado hecho con 5 plazas, y la máquina de helados hecha de los otros 5 casillas. ¡Las posibilidades son infinitas!<br/><br/> Se pregunta por qué estamos haciendo cosas fuera de 10 cuadrados? Es porque en matemáticas, 10 al cuadrado es igual a 100, y al cuadrado sonidos como las plazas!<br/>",
    "standard": " Para que su proyecto agregó a este estudio, por favor enviar un comentario con un enlace. Usted puede encontrar un enlace a su proyecto haciendo clic en el botón \\\"Insertar\\\" en la página del proyecto. El enlace estará directamente debajo del logo de Facebook.\n<br/> Por favor, envíe un solo proyecto no antes de un mes realizado antes del inicio de este estudio de diseño. Sin embargo, puede actualizar su proyecto, y va a ser elegibles de nuevo. Si usted tiene un proyecto antiguo que encajaría, añadir algunas nuevas características y no dude en presentar la versión actualizada!\n<br/> Todos los proyectos deben cumplir con las normas de la comunidad y ser apropiado para todas las edades!\n<br/> Puede tomar algún tiempo para que se añadirán a sus proyectos. Por favor, sea paciente, añadimos proyectos antiguo a más reciente; no hay necesidad de doble post!\n<br/><br/> SDS (arañazos Estudio de Diseño) es un estudio temático donde cualquier Rascador puede presentar un proyecto que coincida con el tema actual, siempre y cuando cumpla con los requisitos indicados anteriormente.\n  Echa un vistazo a este proyecto para ver cómo los nuevos curadores SDS son seleccionados: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nPor favor, no simplemente pedir para ser un conservador!\n<br/><br/> ¿Tiene una idea para un estudio de diseño futuro? Visitar el estudio vinculado a continuación, lea la descripción del estudio, y luego presentar su idea en la forma de un proyecto aquí: <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/> Las preguntas acerca de Scratch Estudio de Diseño? Echa un vistazo a los arañazos artículo de Wiki en él: <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/> Echa un vistazo a esta cuenta para las nuevas actualizaciones en el SDS, los nuevos comisarios de SDS y más! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/> El crédito a @ @ SDScurator1 y SDScurator2 de la miniatura!",
    "curators": " El SDS está comisariada por"
  },
  },
}
