var l10n = {
  "en": {
    "unique":"Remixing is an important part of Scratch! Celebrate it in this Scratch Design Studio!\n        <br/><br/>\n        Remix one of the projects below, and add your own ideas!<br/>\n        <a href=\"https://scratch.mit.edu/projects/86370044/\">https://scratch.mit.edu/projects/86370044/</a> <br/>\n        <a href=\"https://scratch.mit.edu/projects/85132566/\">https://scratch.mit.edu/projects/85132566/</a> <br/>\n        <a href=\"https://scratch.mit.edu/projects/85111610/\">https://scratch.mit.edu/projects/85111610/</a> <br/><br/>\n\n\n        A few suggestions for your remix is to include: <br/>\n        -More sprites: You could add your own character or prop!<br/>\n        -Some sounds: Why not add some music or sound effects?<br/>\n        -Different gameplay or a different story: Your remix doesn't have to be the same! Try changing it to suit your liking!<br/>\n\n        Feel free to use art, sounds, scripts, ideas or anything from other Scratchers, but make sure to give proper credit when doing so!\n        <br/><br/>\n\n        Don't know how to remix? Check out this tutorial!\n        <a href=\"https://scratch.mit.edu/projects/96160058/\">https://scratch.mit.edu/projects/96160058/</a>\n        <br/><br/>",
    "standard":"To have your project added to this studio, please post a comment with a link. You can find a link to your project by clicking the ‘Embed’ button on the project page. The link will be directly below the Facebook logo.\n        <br/>\n        Please submit a single project made no earlier than one month before the start of this Design studio. However, you can update your project, and it'll be eligible again. If you have an older project that would fit, add some new features and feel free to submit the updated version!\n        <br/>\n        All projects must meet the community guidelines and be appropriate for all ages!\n        <br/>\n        It may take some time for your projects to be added. Please be patient, we add projects oldest to newest; no need to double post!\n        <br/><br/>\n\n        SDS (Scratch Design Studio) is a themed studio where any Scratcher can submit a project that matches the current theme so long as it meets the requirements shown above.\n        <!-- No br here as it looks fine without -->\n        Check out this project to see how new SDS curators are selected: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n        Please do not simply ask to be a curator!\n        <br/><br/>\n\n        Do you have an idea for a future design studio? Visit the studio linked below, read the studio description, and then submit your idea in the form of a project here: <a href=\"http://scratch.mit.edu/studios/93627\">http://scratch.mit.edu/studios/93627</a>\n        <br/><br/>\n\n        Questions about Scratch Design Studio? Check out the Scratch Wiki's article on it: <a href=\"http://wiki.scratch.mit.edu/wiki/SDS\">http://wiki.scratch.mit.edu/wiki/SDS</a>\n        <br/><br/>\n\n        Check out this account for new updates on the SDS, new SDS curators and more! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n        <br/><br/>\n\n        Credit to @st19_galla and @CrazyNimbus for the thumbnail!\n\n        <br/",
    "curators":"The SDS is curated by"
  },
  "es": {
    "translator":"Traducción por @mundofinky",
    "unique":"¡Las reinvenciones son una parte importante de Scratch! ¡Celebremos eso en este nuevo Estudio de Diseño de Scratch!\n       <br/><br/>\n        ¡Reinventa uno de los proyectos de abajo y agrega tus propias ideas!<br/>\n       <a href=\"https://scratch.mit.edu/projects/86370044/\">https://scratch.mit.edu/projects/86370044/</a> <br/>\n        <a href=\"https://scratch.mit.edu/projects/85132566/\">https://scratch.mit.edu/projects/85132566/</a> <br/>\n        <a href=\"https://scratch.mit.edu/projects/85111610/\">https://scratch.mit.edu/projects/85111610/</a> <br/><br/>\n\n\n        Unas sugerencias para tu reinvencion es incluir:  <br/>\n        -Más objetos: ¡Podrías agregar tu propio personaje!<br/>\n        -Algunos sonidos: ¿Por qué no agregar música o efectos de sonido?<br/>\n        -Diferente historia o juego: ¡Tu reinvención no tiene que tener lo mismo! ¡Trata de cambiarla a tu gusto!<br/>\n\n        Siéntete libre de usar arte, sonidos, códigos, ideas o cualquier cosa de otros Scratchers, pero asegúrate de darles crédito!\n        <br/><br/>\n\n        ¿No sabes como reinventar un proyecto! ¡Mira este tutorial! (En inglés)\n        <a href=\"https://scratch.mit.edu/projects/96160058/\">https://scratch.mit.edu/projects/96160058/</a>\n        <br/><br/>",
    "standard":"Para tener tu proyecto agregado al estudio, por favor envíe un comentario con un enlace. Puedes encontrar el enlace a tu proyecto haciendo click en el botón "Embed" en la página de tu proyecto. El enlace estará abajo del logo de Facebook.\n        <br/>\n        Por favor publique un solo proyecto no hecho antes de un mes antes de el comienzo de este estudio de diseño. Aunque, puedes actualizar tu proyecto, y será elegible de vuelta. Si tienes un proyecto viejo que podrías agregar a este estudio, ¡agregue algunas nuevas funcionas y envíenos la version actualizada!\n        <br/>\n        Todos los proyectos deben estar de acuerdo con las reglas de la comunidad y ser apropiados para todas las edades.\n        <br/>\n        Puede que tome tiempo para que tu proyecto se agregue. Por favor sea pasiente, agregamos proyectos del más viejo al más nuevo; ¡no hay necesidad de pedirnos dos veces!\n        <br/><br/>\n\n        EDS (Estudio de Diseño de Scratch) es un estudio en donde cualquier Scratcher puede publicar un proyecto que coincida con el tema actual su coincide con los requerimientos mencionados arriba.\n        <!-- No br here as it looks fine without -->\n        Mire este proyecto para ver cómo se seleccionan nuevos curadores del EDS: (En inglés) <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n        ¡Por favor no simplemente pregunte ser un curador!\n        <br/><br/>\n\n        ¿Tienes una idea para un estudio futuro? Visite el enlace de abajo, lea la descripción del estudio, y luego envpia tu idea en forma de un proyecto aquí: <a href=\"http://scratch.mit.edu/studios/93627\">http://scratch.mit.edu/studios/93627</a>\n        <br/><br/>\n\n        ¿Preguntas acerca del Estudio de Diseño de Scratch? Mire el articulo de la Wiki de Scratch: (En inglés) <a href=\"http://wiki.scratch.mit.edu/wiki/SDS\">http://wiki.scratch.mit.edu/wiki/SDS</a>\n        <br/><br/>\n\n        Mire esta cuenta para ver nuevas actualizaciones en el EDS, nuevos curadores del EDS y más: (En inglés) <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n        <br/><br/>\n\n        Crédito a @st19_galla y a @CrazyNimbus por la imagen de este estudio.\n\n        <br/",
    "curators":"Los curadores del EDS son"
  },
  "fr": {
    "translator":"nobody.. yet",
    "unique":"french description here",
    "standard":"french filler text",
    "curators":"Le ACS est organisé par"
  },
  "de": {
    "translator":"Die Übersetzung von LiFayTheGoblin",
    "unique":"german description here",
    "standard":"Um dein Projekt dem Studio hinzuzufügen, poste bitte einen Kommentar mit dem entsprechenden Link. Du kannst den Link zu deinem Projekt finden, indem du auf der Projektseite auf 'Einbinden' klickst. Der link ist direkt unter dem Facebook-Logo.\n        <br/>\n        Reiche bitte nur ein Projekt, das nicht älter als 1 Monat ist, ein. Du kannst aber ein älteres Projekt updaten! Wenn du also ein älteres Projekt hast, das passen würde, füge einige neue Features hinzu und reiche es ein.\n        <br/>\n        Alle Projekte müssen die Community Guidelines befolgen und für alle Altersstufen angemessen sein.\n        <br/>\n        Es kann einige Zeit dauern, bis dein Projekt hinzugefügt wird. Wir bitten um Geduld - du musst den Link nicht erneut posten!\n        <br/><br/>\n\n        SDS (Scratch Design Studio) ist ein Studio, bei dem jeder Scratcher ein Projekt, das zum aktuellen Thema passt und alle Bedingungen erfüllt, einreichen kann.\n        <!-- No br here as it looks fine without -->\n        Schau dir dieses Projekt an, um zu erfahren, wie neue SDS Kuratoren ausgesucht werden (en): <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n        Bitte frag nicht einfach so, ob du Kurator werden kannst!\n        <br/><br/>\n\n        Hast du eine Idee für ein zukünftiges Design Studio? Besuche das unten verlinkte Studio, lies die Studiobeschreibung (en) und reiche dann deine Idee in der Form eines Scratch Projektes ein: <a href=\"http://scratch.mit.edu/studios/93627\">http://scratch.mit.edu/studios/93627</a>\n        <br/><br/>\n\n        Hast du eine Frage über das Scratch Design Studio? Schau dir den Wiki-Artikel darüber an: <a href=\"http://scratch-dach.info/wiki/Scratch_Design_Studio\">http://scratch-dach.info/wiki/Scratch_Design_Studio</a>\n        <br/><br/>\n\n        Dieser Benutzer informiert über SDS-Updates, neue Kuratoren und mehr (en)! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n        <br/><br/>\n\n        Danke an @st19_galla und @CrazyNimbus für das Studiobild!\n\n        <br/",
    "curators":"Die Kuratoren des SDS sind"
  }
}
