var l10n = {
  "en": {
    "language":"English",
    "translator":" ",
    "unique":"Dream up a character for this SDS!\n<br/><br/>Create a new character that could be used as a sprite in someones project. Your character could be anything; an orange dragon, a fluffy cloud, or even a bag of popcorn with a face!<br/><br/>Once you're done, give your character a personality! Write a short description about it, it can be anything; what it likes, hobbies, favorite color, etc.<br/><br/>Be sure to animate your character in some way to give it its own twist!<br/>",
    "standard":"To have your project added to this studio, please post a comment with a link. You can find a link to your project by clicking the ‘Embed’ button on the project page. The link will be directly below the Facebook logo.\n        <br/>\n        Please submit a single project made no earlier than one month before the start of this Design studio. However, you can update your project, and it'll be eligible again. If you have an older project that would fit, add some new features and feel free to submit the updated version!\n        <br/>\n        All projects must meet the community guidelines and be appropriate for all ages!\n        <br/>\n        It may take some time for your projects to be added. Please be patient, we add projects oldest to newest; no need to double post!\n        <br/><br/>\n\n        SDS (Scratch Design Studio) is a themed studio where any Scratcher can submit a project that matches the current theme so long as it meets the requirements shown above.\n        <!-- No br here as it looks fine without -->\n        Check out this project to see how new SDS curators are selected: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n        Please do not simply ask to be a curator!\n        <br/><br/>\n\n        Do you have an idea for a future design studio? Visit the studio linked below, read the studio description, and then submit your idea in the form of a project here: <a href=\"http://scratch.mit.edu/studios/93627/\">http://scratch.mit.edu/studios/93627/</a>\n        <br/><br/>\n\n        Questions about Scratch Design Studio? Check out the Scratch Wiki's article on it: <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n        <br/><br/>\n\n        Check out this account for new updates on the SDS, new SDS curators and more! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n\n<br/",
    "curators":"The SDS is curated by"
  },
  "es": {
    "language":"Español",
    "translator":"Traducción por <a href=\"https://scratch.mit.edu/users/mundofinky/\">@mundofinky</a>",
    "unique":"Translation Needed!",
    "standard":"Para tener tu proyecto agregado al estudio, por favor envíe un comentario con un enlace. Puedes encontrar el enlace a tu proyecto haciendo click en el botón \"Embed\" en la página de tu proyecto. El enlace estará abajo del logo de Facebook.\n        <br/>\n        Por favor publique un solo proyecto no hecho antes de un mes antes del comienzo de este estudio de diseño. Aunque, puedes actualizar tu proyecto, y será elegible de vuelta. Si tienes un proyecto viejo que podrías agregar a este estudio, ¡agregue algunas nuevas funciones y envíenos la versión actualizada!\n        <br/>\n        Todos los proyectos deben estar de acuerdo con las reglas de la comunidad y ser apropiados para todas las edades.\n        <br/>\n        Puede que tome tiempo para que tu proyecto se agregue. Por favor sea paciente, agregamos proyectos del más viejo al más nuevo; ¡no hay necesidad de pedirnos dos veces!\n        <br/><br/>\n\n        EDS (Estudio de Diseño de Scratch) es un estudio en donde cualquier Scratcher puede publicar un proyecto que coincida con el tema actual y cumpla con los requerimientos mencionados arriba.\n        <!-- No br here as it looks fine without -->\n        Mire este proyecto para ver cómo se seleccionan nuevos curadores del EDS: (En inglés) <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n        ¡Por favor no simplemente pregunte ser un curador!\n        <br/><br/>\n\n        ¿Tienes una idea para un estudio futuro? Visite el enlace de abajo, lea la descripción del estudio, y luego envía tu idea en forma de un proyecto aquí: <a href=\"http://scratch.mit.edu/studios/93627/\">http://scratch.mit.edu/studios/93627/</a>\n        <br/><br/>\n\n        ¿Preguntas acerca del Estudio de Diseño de Scratch? Mire el artículo de la Wiki de Scratch: (En inglés) <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n        <br/><br/>\n\n        Mire esta cuenta para ver nuevas actualizaciones en el EDS, nuevos curadores del EDS y más: (En inglés) <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n\n<br/>",
    "curators":"Los curadores del EDS son"
  },
  "fr": {
    "language": "Français",
    "translator": "Traduction par <a href=\"https://scratch.mit.edu/users/smrman/\">@smrman</a>",
    "unique": "Imagine un personnage pour ce SDS!\n<br/><br/>Crée un nouveau personnage qui pourrait être utilisé comme un lutin dans le projet de quelqu'un. Ton personnage peux être n'importe quoi; un dragon orange, un nuage duveteux, ou même un sachet de popcorn avec un visage!<br/><br/>Une fois que c'est fait, donne de la personnalité à ton personnage! Écris une courte description à son propos, cela peut être n'importe quoi; ce qu'il aime, ses hobbys, sa couleur préférée, etc.<br/><br/>Assures-toi d'animer ton personnage pour lui donner son propre style!<br/>",
    "standard": "Pour avoir vos projets ajoutés dans ce studio, postez un commentaire avec le lien. Vous pouvez trouver le lien de votre projet en cliquant le bouton \"Embed\" (Intégré en français) sur la page du projet. Le lien va apparaitre directement en dessous du logo Facebook.\n<br/>S'il-vous-plait, ne soumettez qu'un projet ancien de moins d'un mois avant l'ouverture de ce Studio de Design Scratch (SDS). Toutefois, vous pouvez aussi mettre votre projet à jour et le soumettre pour le studio. Si vous avez d'anciens projets qui pourraient convenir, ajoutez donc des nouvelles fonctionnalités et sentez vous libre de soumettre ce projet renouvelé!\n<br/>Tous les projets doivent suivre les lignes directrices de la communauté et doivent être adaptés pour tous les âges!\n<br/>Il se peut que votre projet mette un peu de temps pour être ajouté. S'il-vous-plait, soyez patient, nous ajoutons les projets des plus anciens aux plus récents; pas besoin donc d'envoyer plusieurs commentaires!\n<br/><br/>Le SDS (Studio de Design Scratch) est un studio à thème où tout Scratcheur peut partager un projet en rapport avec le thème, tant qu'il respecte les règles ci-dessus.\n Découvre ce projet pour voir comment les nouveaux \"conservateurs\"  du SDS sont sélectionnés: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nS'il-te-plaît, ne demande pas simplement pour devenir \"conservateur\"!\n<br/><br/>As-tu une idée pour un futur studio de design? Visite le studio lié ci-dessous, lis la description du studio, et ensuite soumets ton idée ici sous la forme d'un projet: <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Des questions à propos du Studio de Design Scratch? Regardez alors l'article Wiki en rapport avec le SDS (en anglais): <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>Consulte ce compte pour connaître les nouvelles mises à jour sur le SDS, sur les \"conservateurs\" du SDS et plus encore! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/>",
    "curators": "Le SDS est géré par"
  },
  "de": {
    "language":"Deutsch",
    "translator":"Die Übersetzung von <a href=\"https://scratch.mit.edu/users/LiFayTheGoblin/\">@LiFayTheGoblin</a>",
    "unique":"Translation Needed!",
    "standard":"Um dein Projekt dem Studio hinzuzufügen, poste bitte einen Kommentar mit dem entsprechenden Link. Du kannst den Link zu deinem Projekt finden, indem du auf der Projektseite auf 'Einbinden' klickst. Der link ist direkt unter dem Facebook-Logo.\n        <br/>\n        Reiche bitte nur ein Projekt, das nicht älter als 1 Monat ist, ein. Du kannst aber ein älteres Projekt updaten! Wenn du also ein älteres Projekt hast, das passen würde, füge einige neue Features hinzu und reiche es ein.\n        <br/>\n        Alle Projekte müssen die Community Guidelines befolgen und für alle Altersstufen angemessen sein.\n        <br/>\n        Es kann einige Zeit dauern, bis dein Projekt hinzugefügt wird. Wir bitten um Geduld - du musst den Link nicht erneut posten!\n        <br/><br/>\n\n        SDS (Scratch Design Studio) ist ein Studio, bei dem jeder Scratcher ein Projekt, das zum aktuellen Thema passt und alle Bedingungen erfüllt, einreichen kann.\n        <!-- No br here as it looks fine without -->\n        Schau dir dieses Projekt an, um zu erfahren, wie neue SDS Kuratoren ausgesucht werden (en): <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\n        Bitte frag nicht einfach so, ob du Kurator werden kannst!\n        <br/><br/>\n\n        Hast du eine Idee für ein zukünftiges Design Studio? Besuche das unten verlinkte Studio, lies die Studiobeschreibung (en) und reiche dann deine Idee in der Form eines Scratch Projektes ein: <a href=\"http://scratch.mit.edu/studios/93627/\">http://scratch.mit.edu/studios/93627/</a>\n        <br/><br/>\n\n        Hast du eine Frage über das Scratch Design Studio? Schau dir den Wiki-Artikel darüber an: <a href=\"http://scratch-dach.info/wiki/Scratch_Design_Studio/\">http://scratch-dach.info/wiki/Scratch_Design_Studio/</a>\n        <br/><br/>\n\n        Dieser Benutzer informiert über SDS-Updates, neue Kuratoren und mehr (en)! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n        <br/><br/>\n\n        Danke an @st19_galla und @CrazyNimbus für das Studiobild!\n\n        <br/",
    "curators":"Die Kuratoren des SDS sind"
  },
  "id": {
    "language": "Bahasa Indonesia",
    "translator": "Diterjemahkan oleh <a href=\"https://scratch.mit.edu/users/Really_A/\">@Really_A</a>",
    "unique": "Translation Needed!",
    "standard": "Untuk memiliki karyamu ditambahkan kedalam studio ini, harap tinggalkan tautan ke karyamu dalam kolom komentar. Kamu dapat mendapatkan tautan ke karyamu dengan mengklik tombol 'Embed' di halaman karya. Tautan itu berada tepat di bawah logo Facebook.\n<br/>Harap kirimkan sebuah karya yang dibuat tidak lebih awal dari sebulan sebelum dimulainya Studio Desain Scratch ini. Namun, kamu dapat memperbarui karya anda sehingga karya itu memenuhi syarat untuk dimasukkan. Kalau kamu memiliki karya lama yang sesuai, tambahkan beberapa fitur baru dan jangan ragu untuk mengirimkan versi yang telah diperbarui!\n<br/>Semua karya harus memenuhi peraturan komunitas dan layak untuk semua umur!\n<br/>Mungkin diperlukan beberapa waktu sebelum karyamu ditambahkan kedalam studio ini. Harap bersabar, kita menambahkan karya dari yang terlama ke yang terbaru; tidak perlu double post!\n<br/><br/>SDS (Studio Desain Scratch) adalah studio bertema dimana siapapun dapat mengirimkan sebuah karya yang sesuai dengan tema pada waktu itu selama ia memenuhi persyaratan yang ditunjukkan diatas.\n Lihat karya ini untuk melihat bagaimana kurator SDS baru dipilih: (dalam Bahasa Inggris) <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nJangan hanya bertanya untuk menjadi kurator!\n<br/><br/>Apakah kamu memiliki ide untuk Studio Desain Scratch masa depan? Kunjungi tautan studio dibawah ini, baca deskripsinya, dan kemudian ajukan idemu dalam bentuk karya disini: <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Pertanyaan tentang Studio Desain Scratch? Lihat artikel di Scratch wiki tentangnya: (dalam Bahasa Inggris) <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>Lihat akun ini untuk melihat update terbaru di SDS, kurator SDS baru, dan masih banyak lagi! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/>Kredit kepada @st19_galla dan @CrazyNimbus untuk gambar mini!",
    "curators": "SDS ini dikurasi oleh"
  },
    "tr": {
    "language": "Türkçe",
    "translator": "<a href=\"https://scratch.mit.edu/users/-MysteryMaker-/\">@-MysteryMaker-</a> Çeviri",
    "unique": "Translation Needed!",
    "standard": " Proje bu stüdyoya ekledi, bir link ile bir yorum gönderin. Proje sayfasındaki 'göm' düğmesini tıklayarak projenize bir bağlantı bulabilirsiniz. Bağlantı doğrudan Facebook logosunun altında olacaktır.\n<br/>Bu tasarım stüdyosu başlamadan önce erken bir ay daha yapılmış tek bir proje gönderin. Ancak, proje güncelleyebilirsiniz, ve yine uygun olacak. Eğer uyabilecek eski bir projeniz varsa, bazı yeni özellikler eklemek ve güncelleştirilmiş bir sürümünü göndermek için çekinmeyin!\n<br/>Tüm projeler topluluk kurallarına uygun ve her yaş için uygun olmalıdır!\n<br/>Bu sizin projelerin eklenecek için biraz zaman alabilir. Lütfen sabırlı olun, biz yeni projelerin eski ekleyin; çift ​​mesaja gerek yok!\n<br/><br/>SDS (Scratch Design Studio) herhangi Scratcher kadar uzun süre yukarıda gösterilen gereksinimlerini karşılayan güncel tema eşleşen bir proje sunabilir temalı stüdyosu.\n Seçilen nasıl yeni SDS küratörler görmek için bu projeyi göz atın:  <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nbasit bir küratör olmak sormayın lütfen!\n<br/><br/>Eğer gelecekteki bir tasarım stüdyosu için bir fikriniz var mı? , Aşağıda bağlantısı stüdyosunu ziyaret stüdyo açıklamasını okuyun ve sonra burada bir proje şeklinde fikrinizi gönderin: <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Scratch Design Studio hakkında sorularınız mı var? Üzerinde Scratch Wiki makaleye göz atın (EN): <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>SDS yeni güncellemeleri, yeni SDS küratör ve daha fazlası için bu hesabı göz atın! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/>küçük resim için @st19_galla Kredi ve @CrazyNimbus!",
    "curators": "SDS küratörlüğünü"
  },
    "ru": {
    "language": "Русский",
    "translator": "Перебёд от <a href=\"https://scratch.mit.edu/users/SkyShine/\">@SkyShine</a>",
    "unique": "Translation Needed!",
    "standard": "Для того, чтобы мы ваш проект добавлим в студию, пожалуйста, напишите комментировай со ссылкой. Ссылку найдёш на свой проект, нажми на кнопку 'Embed'. Ссылка будет под логотипом Facebook.\n<br/>Пожалуйста зделай один проект сделанный не раньще чем один месяц перед начала этой студии дезайна. Тем не менее, вы можете обновить свой ​​проект, и ево сможма исползобать. Если у вас есть старый проект, вы сможыти добавить некоторые новые функции и не стесняйтесь представить новую версию!\n<br/>Все проекты должны соответствовать принципам сообщества и можно для всех возрастов!\n<br/>Это может быть многа время для ваших проектов которые будут добавлены. Пожалуйста будьте терпеливы, мы добавляем проекты старых к новым; ненадо делать двойной пост!\n<br/><br/>У SDS (Scratch Design Studio) ецть тема, где любой Scratcher может зделать проект, который тоже самой тем, пока она отвечает за бсе прабило выше.\n Проверьте этот проект чтобы увидеть как мы новые SDS кураторы выбираем: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nПожалуста процта не спрашовай быть кыратором!\n<br/><br/>У вас есть идея для будущей Scratch Design Studio? Смотрите на студию (ссылке ниже), прочитайте описание студии описание, и представите свою идею в виде проекта здесь : <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Есть вопросы? Посмотри на вики: <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>Проверьте вот этот пользователь для новых обновлений на SDS, новые кураторы SDS и многое другое! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/>Кредит @st19_galla и @CrazyNimbus для миниатюрами!",
    "curators": "SDS кураторы:"
  },
    "ro": {
    "language": "Română",
    "translator": "<a href=\"https://scratch.mit.edu/users/ScratchVM/\">@ScratchVM</a>",
    "unique": "Translation Needed!",
    "standard": "Pentru a avea proiectul adaugat la acest studio, va rugam sa postati un comentariu cu un link. Poti gasi un link la proiect facand clic pe butonul \\\"Embed\\\" de pe pagina proiectului . Link-ul va fi direct sub logo-ul Facebook .\n<br/>Va rugam sa trimiteti un singur proiect nu mai devreme de o luna, facut inainte de inceperea acestui studio de design . Cu toate acestea, puteti actualiza proiectul si va fi eligibil din nou. Daca aveti un proiect mai vechi, care s-ar potrivi, adauga unele caracteristici noi si nu ezitati sa trimiteti versiunea actualizata!\n<br/>Toate proiectele trebuie sa respecte liniile directoare comunitare si sa fie adecvate pentru toate varstele!\n<br/>Poate dura ceva timp pentru proiectele dvs. sa fie adaugate.Va rugam sa aveti rabdare, vom adauga proiecte mai vechi la cele mai noi; nu este nevoie sa postezi de mai multe ori!\n<br/><br/>SDS (Scratch Design Studio) este un studio tematic unde  oricare Scratcher poate depune un proiect care se potriveste cu tema actuala, atat timp cat acesta indeplineste cerintele prezentate mai sus.\n Verifica acest proiect pentru a vedea modul în care noii SDS curatori sunt selectati : (In limba engleza) <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nVa rugam sa nu intrebati pentru a fii un curator\n<br/><br/>Ai o idee pentru un viitor studio de design? Vizita studio-ul de mai jos,citiți descrierea studioului, si apoi trimite ideea ta sub forma unui proiect aici : <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Intrebari despre Scratch Design Studio? Verifica articolul de pe Scratch wiki despre el: (in engleza) <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>Verificati acest cont pentru actualizari pe SDS,noi curatori SDS si mai multe! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n<br/><br/>Credit lui @st19_galla si @CrazyNimbus pentru imaginea studioilui!",
    "curators": "SDS-ul este curat de"
  },
  
    "nl": {
    "language": "Nederlands",
    "translator": "Vertaling van <a href=\"https://scratch.mit.edu/users/Bouwer2100/\">@Bouwer2100</a>",
    "unique": "Translation Needed!",
    "standard": "Om te zorgen dat je project wordt toegevoegd aan de studio, moet je een reactie plaatsen met een link erin. Je kan een link naar je project vinden door op de 'Delen' knop te drukken op de projectpagina. De link zal recht onder het Facebooklogo staan.\n<br/>Stuur alsjeblieft één project in wat niet eerder dan een maand voor de start van deze Design studio is gemaakt. Maar, je kan je project updaten waardoor je het weer mag insturen. Als je een ouder project hebt wat erbij zou passen, voeg dan wat nieuwe dingen toe en voel je vrij om de nieuwe versie in te sturen!\n<br/>Alle projecten moeten de communityrichtlijnen volgen en geschikt zijn voor alle leeftijden!\n<br/>Het kan een tijdje duren voordat je projecten worden toegevoegd. Wees alsjeblieft geduldig, we voegen projecten toe op volgorde van oud naar nieuw, je hoeft het niet meerdere keren te plaatsen!\n<br/><br/>SDS (Scratch Design Studio) is een studio met een thema waar elke Scratcher een project kan in sturen dat hetzelfde thema heeft als dat van op dit moment, zolang het aan de bovenstaande vereisten voldoet.\n Kijk naar dit project om erachter te komen hoe nieuwe SDS-beheerders worden geselecteerd: (in het Engels) <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a>\nVraag alsjeblieft niet zomaar of je een beheerder kan zijn!\n<br/><br/>Heb je een idee voor een toekomstige design studio? Bezoek de studio die hieronder gelinkt staat, lees de beschrijving van de studio en stuur dan je idee in de vorm van een project hier in: <a href=\"https://scratch.mit.edu/studios/93627/\">https://scratch.mit.edu/studios/93627/</a>\n<br/><br/>Heb je vragen over een Scratch Design Studio? Kijk naar het artikel op de Scratch Wiki dat erover gaat: (in het Engels) <a href=\"http://wiki.scratch.mit.edu/wiki/SDS/\">http://wiki.scratch.mit.edu/wiki/SDS/</a>\n<br/><br/>Kijk naar dit account voor nieuwe updates over de SDS, nieuwe SDS-beheerders en meer! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a>\n\n<br/>",
    "curators": "De SDS wordt beheerd door"
  },
  
  "he": {
    "language": "עִבְרִית",
    "translator": "Scimonster",
    "unique": "תמציא דמות עבור \"סטודיו ליצירה בסקראץ'\" הזה!<br/>ליצור דמות חדשה שאחרים יכולים להשתמש בו בפרויקטים שלהם. הדמות יכולה להיות כל דבר: דרקון כתום, עננים, או אפילו סקיט פופקורן עם פרצוף.<br/>אחרי שסיימת, תן לדמות שלך אישיות! כתוב סיפור קצר עליו, זה יכול להיות כל דבר: מה הוא אוהב, תחביבים, צבע אהוב, וכו'.<br/>אל תשכח להנפיש את הדמות שלך בדרך כלשהו כדי לתת טוויסט מיוחד.",
    "standard": "כדי להוסיף את הפרויקט שלך לסטודיו זה, בבקשה לפרסם תגובה עם קישור. אתה יכול למצוא קישור הפרויקט על ידי לחיצה על כפתור 'Embed' בדף הפרויקט . הקישור יהיה ישר מתחת ללוגו פייסבוק. <br/><br/>אנא שלח פרויקט יחיד שנעשה לא יותר מחודש לפני תחילת סטודיו ליצירה זה. עם זאת , אתה יכול לעדכן את הפרויקט שלך, וזה יהיה זכאי שוב. אם יש לך פרויקט ישן שמתאים, תוסיף כמה תכונות חדשות ושלח את הגרסה המעודכנת! <br/>כל הפרויקטים חייבים לעמוד בהנחיות הקהילה ולהיות מתאימים לכל הגילאים! <br/>זה עלול לקחת קצת זמן עד שיוסיפו את הפרויקט שלך. אנא תמתין בסבלנות, אנחנו מוסיפים פרויקטים מהישן לחדש; אין צורך לשלוח שוב! <br/><br/>SDS (סטודיו ליצירה בסקראץ’) היינו סטודיו עם נושא שבו כל משתמש סקראץ’ יכול להגיש פרויקט שמתאים לנושא הנוכחי כל עוד הוא עומד בדרישות המוצגות לעיל. תסתכל בפרויקט הזה כדי לראות איך אוצרים ל-SDS נבחרים: <a href=\"https://scratch.mit.edu/projects/55738732/\">https://scratch.mit.edu/projects/55738732/</a> נא לא לשאול פשוט להיות אוצר!<br/><br/>יש לך רעיון לסטידו יצירה חדשה? תבקר את הסטודיו (קישור למטה), קרא את תיאור הסטודיו, ושלח את הרעיון שלך בפרויקט: <a href=\"http://scratch.mit.edu/studios/93627/\">http://scratch.mit.edu/studios/93627/</a><br/><br/>שאלות על סטודיו ליצירה בסקראץ’? בדוק את המאמר של Scratch Wiki על זה: (באנגלית)  <a href=\"http://wiki.scratch.mit.edu/wiki/SDS\">http://wiki.scratch.mit.edu/wiki/SDS/</a><br/><br/>בדקו את החשבון הזה עבור עדכונים חדשים על SDS, אוצרי SDS חדשים ועוד! <a href=\"https://scratch.mit.edu/users/SDS-Updates/\">@SDS-Updates</a> <br/><br/>קרדיט ל-@st19_galla  ו-@Malik44 עבור התמונה הממוזערת!",
    "curators": "האוצרים לסטודיו ליצירה בסקראץ’ הם:"
  },
}
